### ISSUE TITLE
Just installed deCONZ 0.13.4 on Homey 4.0.0 and App is crashing when started

### ISSUE THREAD

**Issue by GrimmJok3r** [fantomnotabene/HomeyCONZ#44]
**Describe the bug:**
When installed the app crashed directly
not able to start at all

**How to reproduce:**
Try to restart App
App Shows App had Stopped unexpectedly

Have tried reinstalling but unfortunately it did not help

─────────────── Logging stdout & stderr ───────────────
module.js:550
    throw err;
    ^

Error: Cannot find module '../../node_modules/nbhttp'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/drivers/Driver.js:4:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

--- INFO: ru.notabene.deconz has been killed ---

Thx for your help

**Comment by GrimmJok3r** [comment]
Used Older Node.JS version 12.16.1 LTS and now works
